### ISSUE TITLE
Duplicate titles should not be allowed

### ISSUE THREAD

**Issue by rbp15** [thecoderok/MeasureThat.net#61]
<img width="1156" alt="latest_benchmarks_-_measurethat_net" src="https://cloud.githubusercontent.com/assets/13234172/19061734/3b75434c-89c1-11e6-9935-6959117c34f1.png">
Currently on the site there are multiple "tests" with the same title.  I should see one unique title per test.

**Phase 1:**
Field validation detects title already exists - forces user to change it.

**Phase 2:**
Field validation detects title already exists, forces user to change it, and gives them the option to view the other test(s) with the same title.

**Comment by thecoderok** [comment]
Phase 1 is done

**Comment by thecoderok** [comment]
fixed, benchmarks with duplicates can't be published
<img width="822" alt="image" src="https://github.com/user-attachments/assets/b08403e4-dae5-418e-a495-78495e144d0c">
