### ISSUE TITLE
Test shouldn't be published if it results in an error on run.

### ISSUE THREAD

**Issue by rbp15** [thecoderok/MeasureThat.net#62]
As a user when I visit the latest benchmarks page, I do not want to be able to click on a test that upon running results in an error (attached).

Possible solution:
#1:
- Save button is disabled until the user runs the script.  
- Save button is enabled if script runs without error.  
- When save button is clicked it runs the script and does a final check that the script runs without error.

*An error is defined as a run time error that stops the script from executing - not any other form of error.

**Comment by thecoderok** [comment]
fixed
