### ISSUE TITLE
User should be able to run a test before it is submitted. Related to Issue #62.

### ISSUE THREAD

**Issue by randallbpotter15** [thecoderok/MeasureThat.net#63]
Related to:
https://github.com/thecoderok/MeasureThat.net/issues/62

As a user I want to be able to run a test case before I submit it.
This will ensure I am able to verify a working test before it is made public.
This will also reduce the number of errant tests listed in the main directory.

This will also save database churn as the test is not saved / edited / saved / edited while the user debugs.

**Comment by thecoderok** [comment]
Done
