### ISSUE TITLE
In order to run the test, it should be loaded not on the main page, but rather in the bare iframe

### ISSUE THREAD

**Issue by thecoderok** [thecoderok/MeasureThat.net#64]

**Comment by randallbpotter15** [comment]
Can use a sandbox, allow-scripts iframe for security
`<iframe src="demo_iframe_sandbox.htm" sandbox="allow-scripts">
  <p>Your browser does not support iframes.</p>
</iframe>`

**Comment by thecoderok** [comment]
done
