### ISSUE TITLE
Showing invalid time

### ISSUE THREAD

**Issue by entrptaher** [thecoderok/MeasureThat.net#66]
Previous results are showing invalid time like **2018 years ago**

![image](https://user-images.githubusercontent.com/8284972/35776532-8ac95a2c-09c8-11e8-9d19-460c174e1c8d.png)

**Comment by thecoderok** [comment]
Hi @entrptaher , thank you for reporting that bug!
It was fixed in https://github.com/thecoderok/MeasureThat.net/commit/9df7c1580a8368d73255f38cd69d5db348eb2632 
New results will have correct time
