### ISSUE TITLE
About could list a documentation page explaining tests

### ISSUE THREAD

**Issue by headwinds** [thecoderok/MeasureThat.net#70]
I'd like to do lunch-n-learn demo of measurethat.net to my co-workers   

My first benchmark test was this [one](https://www.measurethat.net/Benchmarks/Show/9761/0/order-variants-find-filter-vs-reduce) and then I forked it to create this [version](https://www.measurethat.net/Benchmarks/Show/9764/0/order-variants-find-filter-vs-reduce-with-10000-records)

This is all excellent! But when I go to explain these tests to my team mates what is the difference between slowest & fastest vs the chart at the bottom? 

In terms of recommending a test, I'm assuming we should go with the chart and choose the test with the lowest bar. Is there any documentation clarifying this?

**Comment by thecoderok** [comment]
Hi! Thank you for this report! 

Chart at the bottom is the visual representation of the "slowest & fastest" table. So the more operations/second, the higher the bar in the chart (meaning the test is faster). Is that what you are asking, or I am missing something?

**Comment by headwinds** [comment]
@thecoderok yes - I'm glad to hear the chart relates to the speed - in my case - my bench mark reveals

FASTEST: 2 loop test (find & filter)
SLOWEST: 1 loop test (reduce)

The 1 loop test has a shorter bar than the 2 loop test. My colleague is telling the me that 1 loop is better but wouldn't this test prove that the 2 loop test actually wins out?! Or am I wrong here?!

In terms of performance, in my mind, when I read fastest - I would think that means it's the most performant - even though its potentially 2 loops (or more like 1.5 due to how find works ;-D). 

You would want to pick the fastest car over the slowest car - the porche over pinto - or we should choose the slowest test unless I'm totally misreading it.  I appreciate your insight.

**Comment by headwinds** [comment]
@thecoderok I re-read your answer again and reviewed the tests again. 

"the more operations/second, the higher the bar in the chart (meaning the test is faster)" 

We should consider the faster test as the winner. 

Thus, even though my colleague thought reduce was faster, this benchmark proves that when dealing with this type of data, it can be slower than find/filter.
