### ISSUE TITLE
Field autocompletion issue

### ISSUE THREAD

**Issue by Sidnioulz** [thecoderok/MeasureThat.net#86]
Hi,

I've recently created a benchmark and my browser autofilled all name fields with my own name :fearful: 

I didn't think to edit the benchmark name, and it now has my own name, and I can't edit or delete it [link](https://www.measurethat.net/Benchmarks/Show/25957/0/). As I created it as a guest, I cannot do anything to remove it. Could you please remove this benchmark, and would you consider disabling autocompletion on name fields on the form to create benchmarks?

Thanks.

**Comment by thecoderok** [comment]
done, removed this benchmark

> No webpage was found for the web address: https://www.measurethat.net/Benchmarks/Show/25957/0/

**Comment by Sidnioulz** [comment]
Thanks!
